name: Brakeman

on:
  workflow_call:
    inputs:
      reporter:
        description: 'Reporter type to use (github-pr-review, github-pr-check, github-check)'
        type: string
        default: 'github-pr-review'
        required: false
      fail_on_error:
        description: 'Whether to fail the workflow if security issues are found'
        type: boolean
        default: true
        required: false
  workflow_dispatch:
    inputs:
      reporter:
        description: 'Reporter type to use'
        type: choice
        options:
          - github-pr-review
          - github-pr-check
          - github-check
        default: 'github-pr-review'
        required: true
      fail_on_error:
        description: 'Fail on security issues'
        type: boolean
        default: true
        required: true

permissions:
  contents: read
  pull-requests: write

jobs:
  scan_ruby:
    name: Brakeman
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
          
      - name: Run Brakeman with reviewdog
        uses: reviewdog/action-brakeman@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: ${{ inputs.reporter }}
          brakeman_version: gemfile
          fail_level: ${{ inputs.fail_on_error && 'error' || 'warning' }}
