name: Rubocop

on:
  workflow_call:
    inputs:
      reporter:
        description: 'Reporter type to use (github-pr-review, github-pr-check, github-check)'
        type: string
        default: 'github-pr-review'
        required: false
      fail_on_error:
        description: 'Whether to fail the workflow if linting errors are found'
        type: boolean
        default: true
        required: false
  workflow_dispatch:
    inputs:
      reporter:
        description: 'Reporter type to use'
        type: choice
        options:
          - github-pr-review
          - github-pr-check
          - github-check
        default: 'github-pr-review'
        required: true
      fail_on_error:
        description: 'Fail on linting errors'
        type: boolean
        default: true
        required: true

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    name: RuboCop
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
          
      - name: Run RuboCop with reviewdog
        uses: reviewdog/action-rubocop@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: ${{ inputs.reporter }}
          rubocop_version: gemfile
          rubocop_flags: '-c .rubocop.yml'
          fail_level: ${{ inputs.fail_on_error && 'error' || 'warning' }}
